### ISSUE TITLE
Probleme to install software.

### ISSUE THREAD

**Issue by pwpwke** [rottaca/LEDTableEngine#40]
Dear, I have already tried several ways to install the software for the Led Table Engine but each time I get the error below. I am using a raspberry pi model 2 B V1. I use the controls you use. They were installed correctly with the information from ADAFRUIT. On review I find this under 20 and 21. The Led matrix is not yet connected.
I don't have much experience with raspberry pi use yet.
I hope you can help me further.
With best regards,
pwpwke

pi@raspberrypi:~/LEDTableEngine $ ./scripts/setup.sh
-- lib2c-dev not found! I2C controller support disabeled.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/LEDTableEngine/build
[ 51%] Built target LEDTableEngine
[ 94%] Built target LEDTableApps
[ 97%] Building CXX object CMakeFiles/LEDTableMain.dir/main.cpp.o
/home/pi/LEDTableEngine/main.cpp:94:18: error: #elif with no expression
             #elif
                  ^
make[2]: *** [CMakeFiles/LEDTableMain.dir/build.make:63: CMakeFiles/LEDTableMain.dir/main.cpp.o] Fout 1
make[1]: *** [CMakeFiles/Makefile2:74: CMakeFiles/LEDTableMain.dir/all] Fout 2
make: *** [Makefile:84: all] Fout 2

**Comment by brockr1993** [comment]
Did you figure this out? I am having the same issue.

**Comment by rottaca** [comment]
Hey,
Looks like a bug in my code. I somehow missed to set the preprocessor define correctly if some optional dependencies are not installed. 

I assume you are running on a raspberry pi. Then, the easiest fix is to install the i2c-dev library. That should solve the issue, even if you don't use the i2c controllers:

`sudo apt-get install i2c-tools`

**Comment by brockr1993** [comment]
I ran that and it stills says lib2c-dev not found. Any other ideas? :(

**Comment by rottaca** [comment]
Did you delete the build folder before building it again?

**Comment by brockr1993** [comment]
Yes. I even deleted the LEDTableEngine and started the clone and setup over and I am still getting the same error.

**Comment by brockr1993** [comment]
Is there anyway we could schedule a time to get together to try and make this happen. I would greatly appreciate it

**Comment by michaelbarbera** [comment]
The project requires an older version of i2c-tools. As a quick fix, I copied [`i2c-dev.h`](https://github.com/fivdi/i2c-bus/blob/master/src/i2c-dev.h) to `/usr/include/linux/`.

**Comment by brockr1993** [comment]
That worked!!
